# Filterbank config
filterbank:
  n_filters: 64
  kernel_size: 20
  stride: 10
# Network config
masknet:
  in_chan: 64
  n_src: 2
  out_chan: 64
  ff_hid: 256
  ff_activation: "relu"
  norm_type: "gLN"
  chunk_size: 100
  hop_size: 50
  n_repeats: 2
  mask_act: 'sigmoid'
  bidirectional: true
  dropout: 0
# Training config
training:
  epochs: 200
  batch_size: 2
  num_workers: 4
  half_lr: yes
  early_stop: yes
  gradient_clipping: 5
# Optim config
optim:
  optimizer: adam
  lr: 0.001
  weight_decay: !!float 1e-5
scheduler:
  steps_per_epoch: 10000
  d_model: 64
# Data config
data:
  json_dir: data/inst2poly/wav44k
  validation_split: 0.1
  n_inst: 1
  n_poly: 4
  task: sep_clean
  sample_rate: 22050
  segment: 5.0
  threshold: 0.1
