# Filterbank config
filterbank:
  n_filters: 64
  kernel_size: 2
  stride: 1
# Network config
masknet:
  in_chan: 64
  n_src: 4
  out_chan: 64
  bn_chan: 128
  hid_size: 128
  chunk_size: 250
  hop_size: 125
  n_repeats: 6
  mask_act: 'sigmoid'
  bidirectional: true
  dropout: 0
# Training config
training:
  epochs: 200
  batch_size: 16
  num_workers: 4
  half_lr: yes
  early_stop: yes
  gradient_clipping: 5
  random_seed: 42
# Optim config
optim:
  optimizer: adam
  lr: 0.001
  weight_decay: !!float 1e-5
# Data config
data:
  json_dir: data/inst2poly/wav44k
  validation_split: 0.1
  n_inst: 1
  n_poly: 4  
  task: sep_clean
  sample_rate: 11025
  segment: 5.0
  threshold: 0.1
