# Filterbank config
filterbank:
  n_filters: 64
  kernel_size: 32
  stride: 4
# Network config
masknet:
  in_chan: 64
  n_src: 2
  out_chan: 64
  ff_hid: 256
  ff_activation: "relu"
  norm_type: "gLN"
  chunk_size: 256
  hop_size: 128
  n_repeats: 9
  mask_act: 'sigmoid'
  bidirectional: true
  dropout: 0
# Training config
training:
  epochs: 100
  batch_size: 1
  num_workers: 4
  half_lr: yes
  early_stop: yes
  gradient_clipping: 5
# Optim config
optim:
  optimizer: adam
  lr: 0.0005
  weight_decay: !!float 1e-5
scheduler:
  steps_per_epoch: 15964
  d_model: 64
# Data config
data:
  json_dir: data/inst2poly/wav44k
  validation_split: 0.1
  task: sep_clean
  sample_rate: 44100
  segment: 131072
  threshold: 0.1
