# Filterbank config
filterbank:
  n_filters: 64
<<<<<<< HEAD
  kernel_size: 32
=======
  kernel_size: 16
>>>>>>> 4e00daa4c4da77bbee6c0109fa4e2c3611217e72
  stride: 4
# Network config
masknet:
  in_chan: 64
  n_src: 2
  out_chan: 64
  ff_hid: 256
  ff_activation: "relu"
  norm_type: "gLN"
  chunk_size: 332
  hop_size: 166
<<<<<<< HEAD
  n_repeats: 5
=======
  n_repeats: 6
>>>>>>> 4e00daa4c4da77bbee6c0109fa4e2c3611217e72
  mask_act: 'sigmoid'
  bidirectional: true
  dropout: 0
# Training config
training:
  epochs: 100
  batch_size: 1
  num_workers: 4
  half_lr: yes
  early_stop: yes
  gradient_clipping: 5
# Optim config
optim:
  optimizer: adam
  lr: 0.0005
  weight_decay: !!float 1e-5
scheduler:
  steps_per_epoch: 8448
  d_model: 64
# Data config
data:
  json_dir: data/inst2poly/wav44k
  validation_split: 0.1
  n_src: 2
  task: sep_clean
  sample_rate: 44100
  segment: 220500
  threshold: 0.1
